apiVersion: v1
kind: ConfigMap
metadata:
  name: observer-agent-config
data:
  CLUSTER_ID: "minikube-dev"
  CENTRAL_URL: "http://observer-core.local:8080/api/agent/push"
  PROM_URL: "http://prometheus:9090"
  PUSH_INTERVAL: "30"
  ENVIRONMENT: "dev"
