apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-agent
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observer-agent
  template:
    metadata:
      labels:
        app: observer-agent
    spec:
      serviceAccountName: observer-agent
      containers:
        - name: observer-agent
          image: observer-agent:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: observer-agent-config
            - secretRef:
                name: observer-agent-secret
