apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observer-agent
  template:
    metadata:
      labels:
        app: observer-agent
    spec:
      containers:
        - name: observer-agent
          image: docker.io/leninfitfreak/observer-agent:sha-b7a7192
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: observer-agent-config
            - secretRef:
                name: observer-agent-secret
