apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observer-agent
  template:
    metadata:
      labels:
        app: observer-agent
    spec:
      containers:
        - name: observer-agent
          image: docker.io/leninfitfreak/ai-observer-agent:dev
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: observer-agent-config
            - secretRef:
                name: observer-agent-secret
