apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
      {{- end }}
      containers:
        - name: product-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

          ports:
            - containerPort: {{ .Values.service.port | default 8081 }}

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          {{- if and .Values.secrets .Values.secrets.vault .Values.secrets.vault.enabled }}
          envFrom:
            {{- if .Values.secrets.vault.dbSecretName }}
            - secretRef:
                name: {{ .Values.secrets.vault.dbSecretName }}
            {{- end }}
            {{- if .Values.secrets.vault.configSecretName }}
            - secretRef:
                name: {{ .Values.secrets.vault.configSecretName }}
            {{- end }}
          {{- end }}
