apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git  # Added .git for consistency
    targetRevision: dev
    path: helm/frontend
    helm:
      valueFiles:
        - values-dev.yaml  # <-- THIS IS THE CRITICAL LINE
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Ensures namespace exists
