apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: dev
    path: helm/frontend  # Adjust this! If the YAML is deep in argocd/applications/dev/, use ../../helm/frontend
    helm:
      valueFiles:
        - values.yaml  # Or just rely on the default values.yaml in the chart
      # parameters: []  # Use this if overriding specific keys
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
