apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git  # Add .git if missing (good practice)
    targetRevision: dev
    path: helm/frontend
    helm:
      valueFiles:
        - values-dev.yaml   # <-- This loads your correct values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Optional: auto-create namespace if missing
