apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kafka
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 26.9.0  # Good stable version
    helm:
      values: |
        auth:
          rootUser: "admin"          # Optional: set root password
          rootPassword: "admin123"   # Change in prod!
        replicaCount: 1              # 1 broker for dev (sufficient)
        persistence:
          enabled: true
          size: 8Gi
        zookeeper:
          enabled: true              # Explicitly enable embedded Zookeeper
          replicaCount: 1
          persistence:
            enabled: true
            size: 8Gi
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true