apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kafka
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 22.1.5   # 👈 VERY IMPORTANT
    helm:
      values: |
        kraft:
          enabled: false

        zookeeper:
          enabled: true
          replicaCount: 1
          persistence:
            enabled: false

        replicaCount: 1

        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true