apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kafka
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 22.1.5
    helm:
      values: |
        kraft:
          enabled: false

        replicaCount: 1

        persistence:
          enabled: false

        image:
          registry: docker.io
          repository: confluentinc/cp-kafka
          tag: 7.6.0
          pullPolicy: IfNotPresent

        zookeeper:
          enabled: true
          replicaCount: 1
          persistence:
            enabled: false
          image:
            registry: docker.io
            repository: confluentinc/cp-zookeeper
            tag: 7.6.0
            pullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true