apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-dev
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
        singleBinary:
          replicas: 1
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
