apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.55.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/observability/loki/values-dev.yaml
    - repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
