apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: dev
    path: observability/otel
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

