apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-postgresql
  namespace: argocd
spec:
  project: leninkart

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.0
    helm:
      releaseName: postgres
      values: |
        architecture: standalone

        auth:
          enablePostgresUser: true
          postgresPassword: postgres
          username: postgres
          password: postgres
          database: leninkart

        primary:
          persistence:
            enabled: true
            size: 8Gi
            storageClass: standard

          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi

        # 🔥 THIS IS THE FIX
        volumePermissions:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/os-shell
            tag: latest

        metrics:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
