apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-dev
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "*"
    helm:
      releaseName: promtail
      values: |
        config:
          clients:
            - url: http://loki.dev.svc.cluster.local:3100/loki/api/v1/push
        tolerations:
          - operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
