apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-externalsecrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy last
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: dev
    path: platform/external-secrets/applications
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

