apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after ESO
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: leninkart
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: dev
    path: platform/vault/config
    directory:
      recurse: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health checks
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/template/metadata/labels
