apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - rbac-read-topology.yaml
  - configmap-env.yaml
  - externalsecret-openai.yaml
  - deployment.yaml
  - service.yaml
