apiVersion: v1
kind: Service
metadata:
  name: leninkart-order-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "order-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http              # ✅ REQUIRED
      port: {{ .Values.service.port }}
      targetPort: http        # maps to containerPort name