apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: main
    path: platform/postgres/staging
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
