apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-staging
  namespace: argocd
spec:
  project: leninkart
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra
    targetRevision: staging
    path: helm/product-service
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
