apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secretstore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: main
    path: platform/external-secrets
    directory:
      recurse: true
      exclude: applications/*
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
