apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-service-config
  namespace: dev
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: product-service-config-secret
    creationPolicy: Owner
  data:
  - secretKey: APP_JWT_SECRET
    remoteRef:
      key: leninkart/product-service/config
      property: jwt_secret
  - secretKey: API_KEY
    remoteRef:
      key: leninkart/product-service/config
      property: api_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-service-config
  namespace: dev
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: order-service-config-secret
    creationPolicy: Owner
  data:
  - secretKey: APP_JWT_SECRET
    remoteRef:
      key: leninkart/order-service/config
      property: jwt_secret
  - secretKey: API_KEY
    remoteRef:
      key: leninkart/order-service/config
      property: api_key
