apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: dev
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.dev.svc.cluster.local:9090
        isDefault: true
      - name: Jaeger
        type: jaeger
        url: http://jaeger-query.dev.svc.cluster.local:16686
      - name: Loki
        type: loki
        url: http://loki.dev.svc.cluster.local:3100
