fullnameOverride: grafana

testFramework:
  enabled: false

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

env:
  GF_AUTH_DISABLE_LOGIN_FORM: "false"
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_USERS_ALLOW_SIGN_UP: "false"
  GF_SERVER_DOMAIN: "127.0.0.1"
  GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.dev.svc.cluster.local
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.dev.svc.cluster.local:3100

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: leninkart
        orgId: 1
        folder: LeninKart
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/leninkart

dashboards:
  leninkart: {}
