apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: dev
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      zipkin:
        endpoint: 0.0.0.0:9411
    processors:
      batch: {}
      memory_limiter:
        limit_mib: 512
    exporters:
      otlp/signoz:
        endpoint: host.docker.internal:4317
        tls:
          insecure: true
      logging: {}
    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          processors: [batch]
          exporters: [otlp/signoz, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/signoz, logging]
