apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: dev
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318
    - name: zipkin
      port: 9411
    - name: prometheus
      port: 8889
