apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leninkart-root # Root app name – clear and unique
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures clean deletion of child apps
spec:
  project: default  # <-- CHANGED TO default (built-in project, allows all repos including Bitnami)
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: dev # Change to main/staging/prod as needed for different roots
    path: argocd/applications/dev # Points to folder with child apps
    directory:
      recurse: true # Includes all YAML files in subdirs if needed
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
