apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: leninkart
  namespace: argocd
spec:
  description: LeninKart DevOps Project

  sourceRepos:
    - https://charts.bitnami.com/bitnami
    - https://github.com/leninfitfreak/*

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"