apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: leninkart
  namespace: argocd
spec:
  description: LeninKart GitOps Project

  sourceRepos:
    - https://github.com/Leninfitfreak/leninkart-infra

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
