apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leninkart-root
  namespace: argocd
spec:
  project: default  # CHANGE FROM leninkart TO default
  source:
    repoURL: https://github.com/Leninfitfreak/leninkart-infra.git
    targetRevision: dev
    path: argocd/applications/dev  # or whatever path has your child apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
