apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-multicluster-scrape-snippet
  namespace: dev
data:
  prometheus-multicluster.yaml: |
    scrape_configs:
      - job_name: 'ai-observer-central-collector'
        static_configs:
          - targets: ['ai-observer-central-collector.dev.svc.cluster.local:8081']

    remote_write:
      - url: http://mimir.dev.svc.cluster.local:9009/api/v1/push