apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: asia-south1-docker.pkg.dev/leninkart-478305/leninkart-db/postgres:16  # Your own pushed image
          env:
            - name: POSTGRES_DB
              value: leninkart
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: root123
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      # Optional initContainer to fix "lost+found" issue on some storage
      initContainers:
        - name: fix-lostfound
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/postgresql/data/lost+found || true']
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi